config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # Let’s add an home page to our app:
  # get "home", to: "pages#home"
  # usually we write this one : root to: "pages#home"
  root to: "pages#home"

  # Let’s add an about page to our app:
   get "about", to: "pages#about"
  # We want to add a contact page:
  get "contact", to: "pages#contact"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
    @members = ["aim", "bim", "cim", "dim", "eim"]
    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <h1> Hi </h1>
    <%= yield %>
  </body>
  <h3> From Deepika </h3>
</html>

app/views/pages/about.html.erb
<h1>Our first view 🚀</h1>
<h1>Our first view 🚀</h1>

app/views/pages/contact.html.erb
<h1>Contact us </h1>
<form action="/contact" method="get">
  <input type="text" name="member"
  value="<%= params[:member] %>" placeholder="Who are you looking for?">
  <input type="submit">
</form>
<ol>
  <% @members.each do |member|%>
    <li> <%= member %> </li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>Welcome home 🏠 </h1>
<%  current_time = Time.now  %>
<%= current_time %>
<%= link_to "Meet our team", contact_path %>
<%= link_to "Contact Us", contact_path %>
<%= link_to "Know more about us", about_path %>